import { uiUtilsWrapAsTemplate } from "../utils/ui";

import {
    MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_AUTOSAVE,
    MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_BUTTONS_TEMPLATE,
    MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_LOGS_CHANNEL_ID,
    MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_MENTIONABLE,
    MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_NAME_TEMPLATE,
    MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_VERIFIED_ROLES
} from "./master-channel-data-keys";

import { DEFAULT_DYNAMIC_CHANNEL_BUTTONS_INTERFACE_SCHEMA } from "./dynamic-channel-defaults";

export const DEFAULT_MASTER_CATEGORY_NAME = "༄ Dynamic Channels",
    DEFAULT_MASTER_CHANNEL_CREATE_NAME = "➕ New Channel",
    DEFAULT_MASTER_MAXIMUM_FREE_CHANNELS = 3;

export const DYNAMIC_CHANNEL_USER_TEMPLATE = uiUtilsWrapAsTemplate( "user" ),
    DEFAULT_DYNAMIC_CHANNEL_NAME_TEMPLATE = DYNAMIC_CHANNEL_USER_TEMPLATE + "'s Channel",
    DEFAULT_DYNAMIC_CHANNEL_BUTTONS_TEMPLATE = DEFAULT_DYNAMIC_CHANNEL_BUTTONS_INTERFACE_SCHEMA.getAllIds(),
    DEFAULT_DYNAMIC_CHANNEL_MENTIONABLE = true,
    DEFAULT_DYNAMIC_CHANNEL_AUTOSAVE = false,
    DEFAULT_DYNAMIC_CHANNEL_LOGS_CHANNEL_ID = null;

export const DEFAULT_MASTER_CHANNEL_DATA_DYNAMIC_CHANNEL_SETTINGS = {
    [ MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_NAME_TEMPLATE ]: DEFAULT_DYNAMIC_CHANNEL_NAME_TEMPLATE,
    [ MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_BUTTONS_TEMPLATE ]: DEFAULT_DYNAMIC_CHANNEL_BUTTONS_TEMPLATE,
    [ MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_MENTIONABLE ]: DEFAULT_DYNAMIC_CHANNEL_MENTIONABLE,
    [ MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_VERIFIED_ROLES ]: [],
    [ MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_LOGS_CHANNEL_ID ]: DEFAULT_DYNAMIC_CHANNEL_LOGS_CHANNEL_ID,
    [ MASTER_CHANNEL_SETTINGS_KEY_DYNAMIC_CHANNEL_AUTOSAVE ]: DEFAULT_DYNAMIC_CHANNEL_AUTOSAVE
};
